// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByjY8aoyudhYE7OvCkKK5RKEfF6R1eUR0',
    appId: '1:1091930546505:web:3ad9f41b90ab08bf68ba98',
    messagingSenderId: '1091930546505',
    projectId: 'kawall',
    authDomain: 'kawall.firebaseapp.com',
    storageBucket: 'kawall.appspot.com',
    measurementId: 'G-WMKYEHH5K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2EwqS3aSC6T0x7kMdREN_IrWOAt8gKT4',
    appId: '1:1091930546505:android:028a9c45313dcc9968ba98',
    messagingSenderId: '1091930546505',
    projectId: 'kawall',
    storageBucket: 'kawall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA7t89F61gJw3bTFOaRtU8-oHXLqXmdpo',
    appId: '1:1091930546505:ios:c4e53de56c532a6968ba98',
    messagingSenderId: '1091930546505',
    projectId: 'kawall',
    storageBucket: 'kawall.appspot.com',
    iosClientId: '1091930546505-2se8gbk39bgc07kt9ukt83goln0gdgcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.kawAll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA7t89F61gJw3bTFOaRtU8-oHXLqXmdpo',
    appId: '1:1091930546505:ios:c4e53de56c532a6968ba98',
    messagingSenderId: '1091930546505',
    projectId: 'kawall',
    storageBucket: 'kawall.appspot.com',
    iosClientId: '1091930546505-2se8gbk39bgc07kt9ukt83goln0gdgcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.kawAll',
  );
}
